// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-check-api/internal/producer (interfaces: Producer)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	producer "github.com/ozoncp/ocp-check-api/internal/producer"
)

// MockProducer is a mock of Producer interface.
type MockProducer struct {
	ctrl     *gomock.Controller
	recorder *MockProducerMockRecorder
}

// MockProducerMockRecorder is the mock recorder for MockProducer.
type MockProducerMockRecorder struct {
	mock *MockProducer
}

// NewMockProducer creates a new mock instance.
func NewMockProducer(ctrl *gomock.Controller) *MockProducer {
	mock := &MockProducer{ctrl: ctrl}
	mock.recorder = &MockProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducer) EXPECT() *MockProducerMockRecorder {
	return m.recorder
}

// SendCheckEvent mocks base method.
func (m *MockProducer) SendCheckEvent(arg0 producer.CheckEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCheckEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCheckEvent indicates an expected call of SendCheckEvent.
func (mr *MockProducerMockRecorder) SendCheckEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCheckEvent", reflect.TypeOf((*MockProducer)(nil).SendCheckEvent), arg0)
}

// SendTestEvent mocks base method.
func (m *MockProducer) SendTestEvent(arg0 producer.TestEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTestEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTestEvent indicates an expected call of SendTestEvent.
func (mr *MockProducerMockRecorder) SendTestEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTestEvent", reflect.TypeOf((*MockProducer)(nil).SendTestEvent), arg0)
}
