// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-check-api/internal/prometheus (interfaces: Prometheus)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPrometheus is a mock of Prometheus interface.
type MockPrometheus struct {
	ctrl     *gomock.Controller
	recorder *MockPrometheusMockRecorder
}

// MockPrometheusMockRecorder is the mock recorder for MockPrometheus.
type MockPrometheusMockRecorder struct {
	mock *MockPrometheus
}

// NewMockPrometheus creates a new mock instance.
func NewMockPrometheus(ctrl *gomock.Controller) *MockPrometheus {
	mock := &MockPrometheus{ctrl: ctrl}
	mock.recorder = &MockPrometheusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrometheus) EXPECT() *MockPrometheusMockRecorder {
	return m.recorder
}

// IncCreateCheck mocks base method.
func (m *MockPrometheus) IncCreateCheck(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncCreateCheck", arg0)
}

// IncCreateCheck indicates an expected call of IncCreateCheck.
func (mr *MockPrometheusMockRecorder) IncCreateCheck(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncCreateCheck", reflect.TypeOf((*MockPrometheus)(nil).IncCreateCheck), arg0)
}

// IncDeleteCheck mocks base method.
func (m *MockPrometheus) IncDeleteCheck(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncDeleteCheck", arg0)
}

// IncDeleteCheck indicates an expected call of IncDeleteCheck.
func (mr *MockPrometheusMockRecorder) IncDeleteCheck(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncDeleteCheck", reflect.TypeOf((*MockPrometheus)(nil).IncDeleteCheck), arg0)
}

// IncUpdateCheck mocks base method.
func (m *MockPrometheus) IncUpdateCheck(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncUpdateCheck", arg0)
}

// IncUpdateCheck indicates an expected call of IncUpdateCheck.
func (mr *MockPrometheusMockRecorder) IncUpdateCheck(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncUpdateCheck", reflect.TypeOf((*MockPrometheus)(nil).IncUpdateCheck), arg0)
}
