# dev environment.

version: '3'
services:

  dev-postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    command: postgres -c max_connections=300 -c log_min_messages=NOTICE
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      #- /tmp/dev-postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # see docs here https://github.com/apple/foundationdb/tree/master/packaging/docker
  dev-zoo:
    image: zookeeper:3.5.6
    hostname: dev-zoo
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=dev-zoo:2888:3888;2181

  dev-kafka:
    image: confluentinc/cp-kafka:5.1.2
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "dev-zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - dev-zoo

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.5.1/16
